version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./:/code
    networks:
      - default
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - default
volumes:
 mongodb:
  
networks:
  default: